name: mayavi_test
dependencies:
- apptools=4.2.1=py27_0
- configobj=5.0.6=py27_0
- envisage=4.4.0=py27_1
- jpeg=8d
- libpng=1.6.17
- libtiff=4.0.6
- mayavi=4.4.0=np19py27_0
- mkl=11.3.3=1
- numpy=1.9.3=py27_3
- openssl=1.0.2h
- pip=8.1.1=py27_1
- pyface=4.4.0=py27_0
- pyqt=4.11.4=py27_6
- python=2.7.11=4
- qt=4.8.7
- setuptools=21.2.1=py27_0
- sip=4.16.9=py27_2
- six=1.10.0=py27_0
- traits=4.4.0=py27_0
- traitsui=4.4.0=py27_0
- vtk=5.10.1=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8

